### ISSUE TITLE
format issues with embedded tab characters in message text

### ISSUE THREAD

**Issue by ab7pa** [kn6plv/meshchat#1]
Since the message database is a tab-delimited file, if there are embedded tab characters in the message text itself then the message display window will show fields which have content bleeding over from parts of the message text.  This usually happens when people cut/copy text from a web page and paste it into the New Message window.

**Comment by ab7pa** [comment]
Example here:

[2022-03-17_07-36.pdf](https://github.com/kn6plv/meshchat/files/8287369/2022-03-17_07-36.pdf)

**Comment by aanon4** [comment]
Any chance you could attach the raw messages file? It should be in /tmp/meshchat
