### ISSUE TITLE
MeshChat Users only showing local user

### ISSUE THREAD

**Issue by ab7pa** [kn6plv/meshchat#2]
For some reason the MeshChat Users box is only showing the local user.  The /tmp/meshchat/users_remote file is zero length.  Currently there are four users on our meshchat zone and the legacy code shows all of them.

**Comment by aanon4** [comment]
Should be fixed now

**Comment by ab7pa** [comment]
Yes!  Works perfectly now!  Thanks very much, Tim.

**Comment by ab7pa** [comment]
Closing issue.  Thanks again!
