### ISSUE TITLE
FR: Clean up the default Messages view and Channels

### ISSUE THREAD

**Issue by csadams** [kn6plv/meshchat#23]
Feature request... or just an idea at this point.... 
The current default view in Mesh Chat shows the "Everything" channel, which is quickly filling up with all sorts of test messages and messages about many different subjects (and from many different "Channels").  It makes the initial view very cluttered and confusing, especially for anyone who does not yet understand how to use Channels.   

An idea for cleaning this up might be to have a "General" channel (or some other name), and make it the default for both posting a message and viewing the message list.  Then folks coming in to Mesh Chat would see "General" messages and not all the mixed up messages from ALL the channels.  The "Everything" channel could still exist to show absolutely everything... but only when explicitly selected by the user.  

A note about channels.... I'm seeing folks create new channels for all sorts of random stuff, and they are getting synced across all servers.  The channel list will soon be a hard-to-use mess.  We should think about how to solve that, which might be done as part of this "default channel" issue.

**Comment by hickey** [comment]
I thought that I had created a similar issue to this a couple of months ago, but I don't see it. The plan that I had was to allow each MeshChat instance to configure the default channel that is used once a user logs in.

**Comment by csadams** [comment]
Sure, allowing each server owner to set the default channel makes sense and should be enough to achieve the same end state.  I might suggest making the default something sensible like a "General" channel, so that most new installs end up in a good, consistent state without requiring any additional documentation or server-owner-education.

**Comment by hickey** [comment]
Work on this issues has been moved over to hickey/meshchat#5.
