### ISSUE TITLE
FR: enable external storage

### ISSUE THREAD

**Issue by csadams** [kn6plv/meshchat#24]
Feature Request...
For those running Mesh Chat on a hAP or other node with a USB port for external storage... give them a way to configure and manage that storage from the node, and to make it available to MeshChat for storage of files.

**Comment by hickey** [comment]
This is already possible. Everything is controlled in the `meshchatconfig.lua` file and configured with the `meshchat_path` variable. Everything under the `meshchat_path` includes the message database and the files.

**Comment by csadams** [comment]
Ok, cool, I must have mis-understood my conversation with Matheson... I thought it wasn't full working yet.  Are there instructions for setting this up?  I guess the last bit, about making it easier to setup/configure from the node (web UI) should be a separate request?

**Comment by hickey** [comment]
There is very little documentation for MeshChat currently. This is really just a matter of setting the USB storage up to get mounted on the file system every time the node boots and then just pointing MeshChat to that location through the configuration files. 

As for making it easier, that is really an AREDN project functionality and I don't have the visibility or the knowledge if this is on their roadmap.

**Comment by csadams** [comment]
Got it.  If you have any pointers or more details for the step of "setting the USB storage up to get mounted on the filesystem...", do let me know. I'll see if I can try it on a device or two here, and maybe start to draft some docs.  

For the UI part, I guess I was thinking that it would be a configuration/setting (or page) in MeshChat (to point to specific storage location), but makes sense that it would need something on the AREDN UI side as well to set up the storage in the first place.  Happy to let that drop for now... though let's keep it in mind in case there's an opportunity in future work.

**Comment by ab7pa** [comment]
@csadams -- here is an AREDN forum post about how to add USB storage to a node.  Is this what you're looking for? https://www.arednmesh.org/content/howto-meshchat-mikrotik-hap-using-extra-usb-storage-files

**Comment by hickey** [comment]
Work on this feature request has been moved over to hickey/meshchat#4.
