### ISSUE TITLE
Feature Request: wiki like functionality

### ISSUE THREAD

**Issue by qwertos** [kn6plv/meshchat#5]
## Problem Statement

As our mesh is growing we're running into a situation where the mesh status screen is becoming too busy. We'd like a distributed website where we could have a curated list of available services. This could also be useful for storing other important mesh documentation.

## Possible implementation

The wiki is stored as markdown files in a git repository on the node, when a change is made through the web interface, it saves and commits the change. Then, `git format-patch` is run and the output is submitted to a hidden meshchat channel (not visible in the chat tab). When the other nodes sync messages, they notice this channel has a new message and runs `git apply` to apply the changes to its local copy.

### Possible problems with this approach

1. Split brain / Merge conflicts
2. Requires too much space / processing power for nodes

**Comment by qwertos** [comment]
(TBH, I'm not entirely happy with that possible implementation, but the way I'd prefer to do it requires `alfred`.)

**Comment by aanon4** [comment]
Surely this is a new application?

**Comment by qwertos** [comment]
I could see it going either way, but you're not wrong.

After thinking about it some more I have thoughts on how I could implement at least some of what I'm looking for. Withdrawn for now.

**Comment by aanon4** [comment]
I encourage you to make something new!

I dont have plans to do much with MeshChat beyond maintenance. I only took this over because we needed to move it from the original perl implementation.
