### ISSUE TITLE
meshchat-api_2.7_all.ipk shows as version 2.0 once installed

### ISSUE THREAD

**Issue by nathantcampbell** [kn6plv/meshchat#8]
This device has only ever had API pakcage 1.02, 2.6, and now 2.7 installed. Latest 2.7 version is now installed, (confirmed by removing the package then reinstalling) however it's still labeled as 2.0 in the package manager. I'm sure this is just a label change in the IPK

![meshchat](https://user-images.githubusercontent.com/24758209/222824718-58ad50e6-baf8-408e-8f8f-c4127a53350f.JPG)

**Comment by aanon4** [comment]
Looks like I wasn't updating the control file for the api package. Should now be fixed if you'd like to uninstall the api package and download + try the new one? I did not bump the version number for this fix.

**Comment by nathantcampbell** [comment]
I just checked it, you can mark it as resolved. Thanks Tim

Nathan Campbell
