### ISSUE TITLE
Both package cannot be installed at the same time

### ISSUE THREAD

**Issue by kodiakastu** [kn6plv/meshchat#9]
Hi. Every time I install both package, both functionality breaks and neither of my meshchat is completely functionnal. Is this intended / a known issue ?

I'd like to have a vm having meshchat connected to a node that acts like a gateway in my shack. In case of power outage the node can continue to be available for chat until power is back and the vm can do the chat and file sharing again.

I'm sorry if I cannot convey properly what I want to do, English is not my first language :S

**Comment by aanon4** [comment]
You shouldnt need to install both. The non-api version includes the api too.

**Comment by kodiakastu** [comment]
Then Im doing something wrong. 

Im stuck with my vm not synching if the api package is not installed. Could it be that the meshchat zone is not properly advertised if I have both?

(Both being the node and vm. Because I cannot advertise a zone twice on the same node)

**Comment by aanon4** [comment]
So the apionly package is very simple - this being the only part that does anything (https://github.com/kn6plv/meshchat/blob/master/apionly/data/www/cgi-bin/meshchat). This just lets the remote app retrieve a list of all nodes in the requested zone. This code also exists in the non-apionly version and takes the same arguments. I've looked at it a bit (but I dont run this service myself) and I can't see a difference.

So .. here's a test. Install the apionly version and your VM and make sure that's working. Then without changing anything else, remove the api version, install the non-api version and see if your VM still works.

**Comment by kodiakastu** [comment]
After doing what you were suggesting, it works. So the issue is really about how meshchat zones are passed. AREDN nodes won't let met advertise twice the same zone and if I remove my VM from the list, other nodes won't synch against it. 

Do you know a way around the GUI limitation, or I will break something having the same node advertise twice the same meshchat zone ?

**Comment by aanon4** [comment]
So no - an AREDN node wont let you have the same service name twice (nothing related to MeshChat). You would need to have two nodes and publish you VM and non-VM meshchat from different nodes.

**Comment by kodiakastu** [comment]
Thanks a lot for your quick help!
